name: Warrant Node

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Setup Node Env
        uses: actions/setup-node@v3
      - name: Build
        run: |
          npm ci
          npm run build
